CREATE TABLE IF NOT EXISTS restaurantes
(
    id_restaurantes   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100),
    ubicacion VARCHAR(100),
    tipo_cocina  VARCHAR(100),
    disponible BOOLEAN,
    id_reserva  INT,
    PRIMARY KEY (id_restaurantes)
);

CREATE TABLE IF NOT EXISTS reservas
(
    id_reserva        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_restaurantes   INT,
    fecha_reserva DATE,
    nombre_cliente VARCHAR(100),
    telefono_cliente VARCHAR(20),
    PRIMARY KEY (id_reserva),
    FOREIGN KEY (id_restaurantes) REFERENCES restaurantes (id_restaurantes)
);

INSERT INTO restaurantes (name, ubicacion, tipo_cocina, disponible)
VALUES ('Restaurante XYZ', 'Madrid', 'Comida Mexicana', true);
INSERT INTO restaurantes (name, ubicacion, tipo_cocina, disponible)
VALUES ('Restaurante ABC', 'Madrid', 'Comida Italiana', false);
INSERT INTO restaurantes (name, ubicacion, tipo_cocina, disponible)
VALUES ('Restaurante LMN', 'Valencia', 'Comida Valenciana', true);
INSERT INTO restaurantes (name, ubicacion, tipo_cocina, disponible)
VALUES ('Restaurante PQR', 'A Coruña', 'Comida Gallega', true);


